import Link from "next/link"; // Ensure Link is imported for navigation
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4">
          <ul className="flex space-x-6">
            <li>
              <Link href="/" className="text-white hover:text-gray-300">
                Home
              </Link>
            </li>
            <li>
              <Link href="/send-email" className="text-white hover:text-gray-300">
                Send Email
              </Link>
            </li>
            <li>
              <Link href="/contact-lists" className="text-white hover:text-gray-300">
                Contact Lists
              </Link>
            </li>
            <li>
              <Link href="/email-templates" className="text-white hover:text-gray-300">
                Email Templates
              </Link>
            </li>
            <li>
              <Link href="/campaigns" className="text-white hover:text-gray-300">
                Campaigns
              </Link>
            </li>
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
